### ISSUE TITLE
Getting 404 on deeper-zoom tiles

### ISSUE THREAD

**Issue by quite** [stamen/maps.stamen.com#129]
I'm getting quite a lot of 404:s at especially zoom level 11 and deeper. Examples:

    https://stamen-tiles-c.a.ssl.fastly.net/terrain/11/571/971@2x.png
    https://stamen-tiles-d.a.ssl.fastly.net/terrain/12/2225/1578@2x.png

This is one of my first own hacks using Leaflet, but I see the problems on the leaflet-providers preview page as well:

  https://leaflet-extras.github.io/leaflet-providers/preview/

I'm playing down at the Messina strait of Italy, and some tiles at a particular zoom-level do appear properly. Seems to affect Toner and Watercolor as well.

**Comment by loganwilliams** [comment]
dupe #107

**Comment by alexannmill** [comment]
I was having the same issue with the toner layer. I grabbed the URL straight from the stamen site (http://maps.stamen.com/#terrain)and fixed the issue. I hope this works for you too! 

https://stamen-tiles.a.ssl.fastly.net/terrain/{z}/{x}/{y}.jpg

**Comment by deklesen** [comment]
@alexannmill The link you provided does not provide the tiles I am looking for, e.g.
https://stamen-tiles.a.ssl.fastly.net/watercolor/16/34047/22424.jpg

Also, I tried using the tile-link from watercolormaps.collection.cooperhewitt.org, which does not work either:
https://watercolormaps.collection.cooperhewitt.org/tile/watercolor/16/34047/22424.jpg

Finally, I created an account at StadiaMaps and in the Docs, there is this bit:
![image](https://github.com/stamen/maps.stamen.com/assets/19559859/e8e92341-64de-4633-8b91-0f54a2232d80)

Seems like these tiles are just fundamentally missing. A huge bummer, since they are quite cool.
