### ISSUE TITLE
Add the ability to donate to the project

### ISSUE THREAD

**Issue by ericrodenbeck** [stamen/maps.stamen.com#71]
Something like this, from brainpickings

![screen shot 2016-05-03 at 2 33 28 pm](https://cloud.githubusercontent.com/assets/450233/15002339/0d25f3b8-1155-11e6-90f5-d27104dc7dd4.png)

**Comment by CritiqalPete** [comment]
Totally. Put it up and test the waters. See if anyone bites. Let them volunteer comments about their interests. 
Build market intel and it might turn out a crowdfunding campaign will be an option. 
Offering a few "levels" of donation is important as well. 
See if you think the story of maps.stamen is due for an update. 
More soon. 
-Pete

**Comment by alecburch** [comment]
@sconnelley, hoping this will be fairly straightforward to implement. The new donate section is the same width as the "Fork on GitHub/Read about it" area on the right side. We'll have to relocate those two to below the descriptions of each map. Otherwise the map images and text should remain unchanged. 

<img width="683" alt="screen shot 2016-07-10 at 11 40 53 am" src="https://cloud.githubusercontent.com/assets/5263476/16715389/33183482-4693-11e6-805f-35e0451aabc3.png">

**Comment by sconnelley** [comment]
![image](https://cloud.githubusercontent.com/assets/565486/16740855/dc7b3c5a-476e-11e6-96c4-cbc273690c99.png)

**Comment by sconnelley** [comment]
@alecburch -> How do you want to handle the success and error results.  Currently, I am redirecting checkouts back to home page.
If their successful, users see:
![image](https://cloud.githubusercontent.com/assets/565486/16741129/f1bb33c6-476f-11e6-8dc0-8b9f82955d36.png)

Errors:
![image](https://cloud.githubusercontent.com/assets/565486/16741202/47f2af26-4770-11e6-90be-5c71eaf68c92.png)

**Comment by almccon** [comment]
There's also the fullscreen version of each of the maps pages: for example http://maps.stamen.com/terrain instead of http://maps.stamen.com/#terrain. Can we put a subtle donate link on those pages, that shoots you over to the https://stamen.com/opensource/ page maybe?

Perhaps a third yellow button next to `<image>` and `<embed>` that says `donate!` ?

**Comment by alecburch** [comment]
Works for me. So something like this on the full screen pages:

![screen shot 2016-08-03 at 9 18 06 am](https://cloud.githubusercontent.com/assets/5263476/17373051/59de24fc-595b-11e6-80c7-72ca1c7a0ce1.png)

And like this on maps.stamen.com:

![screen shot 2016-08-03 at 9 18 33 am](https://cloud.githubusercontent.com/assets/5263476/17373067/6ad1f95a-595b-11e6-8e34-8f087626467d.png)

**Comment by almccon** [comment]
Currently, we can't deploy braintree on maps.stamen.com because that subdomain doesn't support SSL. So, on both the main maps.stamen.com page _and_ the fullscreen map pages we just need a simple link to https://stamen.com/opensource/.

We can worry about integrating the full braintree donation page at some later date. So @sconnelley's [braintree](https://github.com/stamen/maps.stamen.com/tree/braintree) branch will just sit there unused for a while.

**Comment by almccon** [comment]
I see in #40 that we already have buttons for `<image>` and `<embed>` somewhere on the main page, just hidden. I'm not sure where they would show up on the page. Also in the upper right? If it makes things easier, we could also enable those when we add the donate button, and then we could (presumably) use the same code for the main page and for the fullscreen maps.

**Comment by ericsoco** [comment]
Donate links in PR:
https://github.com/stamen/maps.stamen.com/pull/76

**Comment by CritiqalPete** [comment]
Might consider "Support" vs "Donate". Not sure which is stronger but always best to make a conscious choice. What is the message? Technology? Knowledge? Power/democracy, etc. keep the core values in mind and iterate as much as possible. 
Really glad to see this move forward!
-Pete
